// npm run credits — writes CREDITS.md from the bundled mod entries: community/*.json and src/data/defaults/*.json.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { Provenance } from '../src/lib/community.ts'

const ROOT = new URL('../', import.meta.url)
export const CREDITS_PATH = fileURLToPath(new URL('CREDITS.md', ROOT))

export function bundledEntries(): Provenance[] {
  return ['community/', 'src/data/defaults/'].flatMap((dir) => readdirSync(new URL(dir, ROOT)).filter((n) => n.endsWith('.json')).sort()
    .map((n) => JSON.parse(readFileSync(new URL(dir + n, ROOT), 'utf8')) as Provenance))
}

const cell = (s: string) => s.replace(/\|/g, '\\|')
const source = (s: string) => /^https?:\/\//.test(s) ? `[${new URL(s).hostname}](${s})` : cell(s)

export function renderCredits(entries = bundledEntries()): string {
  const rows = entries.toSorted((a, b) => a.title.localeCompare(b.title))
    .map((e) => `| ${cell(e.title)} | ${e.role} | ${cell(e.author)} | ${cell(e.licence)} | ${source(e.source)}${e.posted ? ` (${e.posted})` : ''} |`)
  return `<!-- Generated by npm run credits from the mod entries; do not edit -->
# Credits

The mods bundled with Galaxy Genome Quest Editor. Default mods preload on a new visitor's home; library mods list on the Library page.

| Mod | Role | Author | Licence | Source |
| --- | --- | --- | --- | --- |
${rows.join('\n')}
`
}

if (process.argv[1] === fileURLToPath(import.meta.url)) writeFileSync(CREDITS_PATH, renderCredits())
